apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  message: "Hello from ConfigMap!"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  db_password: "your_database_password"
