apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: config-volume
            mountPath: /message.txt
          - name: secret-volume
            mountPath: /secret
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: secret-volume
        secret:
          secretName: app-secret
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # Adjust if using a different workload type (e.g., ReplicaSet)
    name: nginx # Adjust if your pod is managed by a different resource
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: my-efs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Adjust storage request as needed

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
spec:
  minAvailable: 2 # Minimum desired available pods
  selector:
    matchLabels:
      app: nginx # Adjust selector to match your pod labels