apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  storageClassName: my-efs-sc # Replace with your StorageClass name
  capacity:
    storage: 1Gi # Adjust storage size as needed
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <EFS endpoint> # Replace with your EFS ID and access point
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-efs-sc
provisioner: efs.csi.aws.com # Replace if using a different provisioner
